import type { LucideIcon } from 'lucide-react';
import {
  ShoppingCart,
  Coffee,
  Car,
  Home,
  Zap,
  Wifi,
  Heart,
  Briefcase,
  Utensils,
  Bus,
  Plane,
  Gift,
  BookOpen,
  Music,
  Film,
  Gamepad2,
  Dumbbell,
  Pill,
  Stethoscope,
  Shirt,
  Baby,
  Dog,
  GraduationCap,
  Landmark,
  PiggyBank,
  CreditCard,
  Banknote,
  TrendingUp,
  Receipt,
  Tag,
  Smartphone,
  Monitor,
  Wrench,
  Palette,
  TreePine,
  Droplets,
  Flame,
  Bike,
  ShoppingBag,
} from 'lucide-react';

// ─── Icon options ─────────────────────────────────────────────────────────────

export interface IconOption {
  name: string;
  Icon: LucideIcon;
}

export const ICON_OPTIONS: IconOption[] = [
  { name: 'ShoppingCart', Icon: ShoppingCart },
  { name: 'ShoppingBag', Icon: ShoppingBag },
  { name: 'Utensils', Icon: Utensils },
  { name: 'Coffee', Icon: Coffee },
  { name: 'Car', Icon: Car },
  { name: 'Bus', Icon: Bus },
  { name: 'Bike', Icon: Bike },
  { name: 'Plane', Icon: Plane },
  { name: 'Home', Icon: Home },
  { name: 'Zap', Icon: Zap },
  { name: 'Wifi', Icon: Wifi },
  { name: 'Heart', Icon: Heart },
  { name: 'Briefcase', Icon: Briefcase },
  { name: 'Gift', Icon: Gift },
  { name: 'BookOpen', Icon: BookOpen },
  { name: 'Music', Icon: Music },
  { name: 'Film', Icon: Film },
  { name: 'Gamepad2', Icon: Gamepad2 },
  { name: 'Dumbbell', Icon: Dumbbell },
  { name: 'Pill', Icon: Pill },
  { name: 'Stethoscope', Icon: Stethoscope },
  { name: 'Shirt', Icon: Shirt },
  { name: 'Baby', Icon: Baby },
  { name: 'Dog', Icon: Dog },
  { name: 'GraduationCap', Icon: GraduationCap },
  { name: 'Landmark', Icon: Landmark },
  { name: 'PiggyBank', Icon: PiggyBank },
  { name: 'CreditCard', Icon: CreditCard },
  { name: 'Banknote', Icon: Banknote },
  { name: 'TrendingUp', Icon: TrendingUp },
  { name: 'Receipt', Icon: Receipt },
  { name: 'Tag', Icon: Tag },
  { name: 'Smartphone', Icon: Smartphone },
  { name: 'Monitor', Icon: Monitor },
  { name: 'Wrench', Icon: Wrench },
  { name: 'Palette', Icon: Palette },
  { name: 'TreePine', Icon: TreePine },
  { name: 'Droplets', Icon: Droplets },
  { name: 'Flame', Icon: Flame },
];

// ─── Color options ────────────────────────────────────────────────────────────

export const COLOR_OPTIONS = [
  '#EF4444',
  '#F97316',
  '#F59E0B',
  '#EAB308',
  '#84CC16',
  '#22C55E',
  '#14B8A6',
  '#06B6D4',
  '#3B82F6',
  '#6366F1',
  '#8B5CF6',
  '#A855F7',
  '#D946EF',
  '#EC4899',
  '#F43F5E',
  '#78716C',
];
